npm i @material-ui/core
npm i @material-ui/icons
npm i @material-ui/lab
npm i @types/node@latest
npm i typescript@latest
npm i @material-ui/lab@latest
npm i @material-ui/core@latest
npm i @types/jest@latest
npm i @testing-library/user-event@latest
npm i @testing-library/react@latest
npm i @testing-library/jest-dom@latest
